"""empty message

Revision ID: f62dd7b2a0bd
Revises: 0a65c10b33db
Create Date: 2023-12-08 22:54:26.305682

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f62dd7b2a0bd'
down_revision = '0a65c10b33db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('email')
        batch_op.drop_column('nomor_telepon')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', mysql.VARCHAR(length=120), nullable=False))
        batch_op.add_column(sa.Column('nomor_telepon', mysql.VARCHAR(length=20), nullable=False))
        batch_op.create_index('email', ['email'], unique=False)

    # ### end Alembic commands ###
